# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
  imageRepo: 'ingeb0rga/azuredevops'
  dockerFilePath: '**/Dockerfile'
  dockerRegistry: 'dockerhub'

stages:
- stage: Setup_Run_Test
  jobs:
    - job: Setup_Run_Test
      steps:
        - task: UsePythonVersion@0
          displayName: Setup Python'
          inputs:
            versionSpec: '3.10'
            addToPath: true
            architecture: 'x64'


        - task: PythonScript@0
          displayName: 'Run calculator'        
          inputs:
            scriptSource: 'filePath'
            scriptPath: 'main.py'
            arguments: 'add 3 5'


        - script: python3 -u -m unittest tests/tests.py
          displayName: 'Run tests'


- stage: Build
  dependsOn: Setup_Run_Test
  jobs:
    - job: Container_build
      steps:
        - task: Docker@2
          displayName: Build and push docker container
          inputs:
            containerRegistry: $(dockerRegistry)
            repository: $(imageRepo)
            command: 'buildAndPush'
            Dockerfile: $(dockerFilePath)
            tags: 
              latest
              $(tag)
