# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Run_and_Test
  jobs:
    - job: Setup_Python
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.10.7'
            addToPath: true
            architecture: 'x64'
          # displayName: Setup Python
    - job: Run_calculator
      dependsOn: Setup_Python
      steps:
        - task: PythonScript@0
          inputs:
            scriptSource: 'filePath'
            scriptPath: 'main.py'
            arguments: 'add 3 5'
          # displayName: 'Run calculator'
    - job: Run_tests
      dependsOn: Run_calculator
      steps:
        - script: python3 -u -m unittest tests/tests.py
          # displayName: 'Run tests'

# - stage: Build
#   jobs:
#     - job: Echo
#       script: echo "Hello"
