# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hello, world!

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.7'
    addToPath: true
    architecture: 'x64'
  displayName: Setup Python
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'main.py'
    arguments: 'add 3 5'
  displayName: 'Run calculator'


- script: python3 -u -m unittest tests/tests.py
  displayName: 'Run tests'

# - task: PythonScript@0
#   inputs:
#     scriptSource: 'filePath'
#     scriptPath: 'python3 -u -m unittest tests/tests.py'
#     # arguments: ''
#   displayName: 'Run tests'
